canonical/katib-operators

charms/katib-ui/metadata.yaml
=> feat: version bump katib-ui image 0.12.0->0.14.0.rc0

charms/katib-db-manager/metadata.yaml
=> feat: version bump katib-db-manager image 0.12.0->0.14.0.rc0

charms/katib-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/katib-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
https://warthogs.atlassian.net/browse/KF-549
update charm libs
=> update charm libs

charms/katib-controller/metadata.yaml, charms/katib-controller/src/early-stopping.json, charms/katib-controller/src/metrics-collector-sidecar.json, charms/katib-controller/src/suggestion.json, charms/katib-db-manager/metadata.yaml, charms/katib-ui/metadata.yaml
=> chore: Bump image versions

charms/katib-controller/src/crds.yaml, charms/katib-controller/src/enasCPUTemplate.yaml, charms/katib-controller/src/pytorchJobTemplate.yaml
Changes to match v0.14.0 release
=> feat: update crd and trial templates to match v0.14.0 release

.github/workflows/integrate.yaml, charms/katib-controller/src/charm.py, charms/katib-controller/src/webhooks.yaml, examples/v1beta1/hp-tuning/random.yaml
=> Backport webhook cert fixes

charms/katib-ui/src/charm.py, examples/v1beta1/hp-tuning/grid-example.yaml, test-requirements.txt, tests/integration/test_charms.py, tox.ini
Added test to Create an Experiment and make sure it completed entirely using lightkube.
=> Extend Katib Integration Tests

charms/katib-controller/metadata.yaml, charms/katib-db-manager/metadata.yaml, charms/katib-ui/metadata.yaml
bump images from 0.14.0 -> 0.15.0-rc.1 for 1.7 release
=> Upgrade images to 0.15.0-rc.1

charms/katib-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/katib-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/katib-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/katib-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py
- Library charms.grafana_k8s.v0.grafana_dashboard updated to version 0.24.
- Library charms.observability_libs.v0.juju_topology updated to version 0.6.
- Library charms.observability_libs.v1.kubernetes_service_patch updated to version 1.5.
=> chore: bump all charm libs

charms/katib-controller/metadata.yaml, charms/katib-controller/src/defaultTrialTemplate.yaml, charms/katib-controller/src/early-stopping.json, charms/katib-controller/src/enasCPUTemplate.yaml, charms/katib-controller/src/metrics-collector-sidecar.json, charms/katib-controller/src/pytorchJobTemplate.yaml, charms/katib-controller/src/suggestion.json, charms/katib-db-manager/metadata.yaml, charms/katib-ui/metadata.yaml
feat: version bump 0.15.0-rc.1->0.15.0
=> feat: version bump 0.15.0-rc.1->0.15.0

charms/katib-controller/metadata.yaml, charms/katib-db-manager/metadata.yaml, charms/katib-ui/metadata.yaml
this interface is not used anywhere, thus, remove it
=> Remove http interfaces

charms/katib-db-manager/src/charm.py
Suumary of changes:
- Added defer event in case when cannot connect to container.
=> fix: added defer event

charms/katib-db-manager/src/charm.py
Summary of changes:
- Removed defer in main event handler.
- Added skip for WaitingStatus in update status handler.
=> fix: remove defer and add wait skip

charms/katib-controller/tox.ini, charms/katib-db-manager/tox.ini, charms/katib-ui/tox.ini
Updates tox.ini's `update-requirements` as described in https://github.com/canonical/argo-operators/pull/100
=> update tox.ini's update-requirements

.github/workflows/integrate.yaml, charms/katib-controller/requirements-integration.in, charms/katib-controller/requirements-integration.txt, charms/katib-db-manager/requirements-integration.in, charms/katib-db-manager/requirements-integration.txt, requirements-integration.in, requirements-integration.txt
ci: update juju to 3.1 and microk8s to 1.25
=> ci: update juju to 3.1 and microk8s to 1.25

charms/katib-controller/CONTRIBUTING.md, charms/katib-db-manager/CONTRIBUTING.md, charms/katib-ui/CONTRIBUTING.md
Added contributing docs for all charms.
=> Kf 4516 Add CONTRIBUTING.md files

charms/katib-controller/requirements-integration.txt, charms/katib-controller/requirements-unit.txt, charms/katib-controller/requirements.txt, charms/katib-db-manager/requirements-integration.txt, charms/katib-db-manager/requirements-unit.txt, charms/katib-db-manager/requirements.txt, charms/katib-ui/requirements.txt
Part of canonical/bundle-kubeflow#868
=> build: bump ops to latest possible version

charms/katib-db-manager/requirements-integration.txt
Build charmed-kubeflow-chisme for requirements-integration.txt.
Part of canonical/charmed-kubeflow-chisme#104
=> build, tests: bump charmed-kubeflow-chisme 0.4.0 -> 0.4.1

charms/katib-controller/requirements-unit.txt, charms/katib-controller/requirements.txt, charms/katib-db-manager/requirements-unit.txt, charms/katib-db-manager/requirements.txt, charms/katib-ui/requirements.txt
Part of canonical/bundle-kubeflow#883
=> build: bump jinja2 3.1.x -> 3.1.4

.github/workflows/integrate.yaml, tox.ini
=> fix(ci): Run tests in `testing` namespace and add logging

charms/katib-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/katib-controller/lib/charms/loki_k8s/v1/loki_push_api.py, charms/katib-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py, charms/katib-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/katib-controller/requirements-unit.txt, charms/katib-controller/requirements.txt, charms/katib-db-manager/lib/charms/data_platform_libs/v0/data_interfaces.py, charms/katib-db-manager/lib/charms/loki_k8s/v1/loki_push_api.py, charms/katib-db-manager/lib/charms/observability_libs/v1/kubernetes_service_patch.py, charms/katib-ui/lib/charms/loki_k8s/v1/loki_push_api.py, charms/katib-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py
* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184
=> chore: bump libraries

charms/katib-controller/metadata.yaml, charms/katib-db-manager/metadata.yaml
Close https://warthogs.atlassian.net/browse/KF-6970
Close https://warthogs.atlassian.net/browse/KF-6971
=> chore: integrate katib-{controller,db-manager} rocks for 0.18.0-rc.0

.github/workflows/ci.yaml, .github/workflows/promote.yaml
=> chore: migrate GH runners to ubuntu 24.04

charms/katib-controller/terraform/versions.tf, charms/katib-db-manager/terraform/versions.tf, charms/katib-ui/terraform/versions.tf
Updating juju provider requirement to >=0.14.0
=> [KF-7255] Update Juju provider

charms/katib-controller/terraform/variables.tf, charms/katib-controller/terraform/versions.tf, charms/katib-db-manager/terraform/variables.tf, charms/katib-db-manager/terraform/versions.tf, charms/katib-ui/terraform/variables.tf, charms/katib-ui/terraform/versions.tf
Cutting new release for branch track/0.18
=> [KF-7254] Release 1.10

charms/katib-controller/terraform/variables.tf, charms/katib-db-manager/terraform/variables.tf, charms/katib-ui/terraform/variables.tf
=> [KF-7268] chore: pin channel to latest/edge

.github/workflows/tiobe_scan.yml, charms/katib-controller/tox.ini, charms/katib-db-manager/tox.ini, charms/katib-ui/tox.ini
Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file
=> [KF-7281] Enabling TIOBE scan

charms/katib-controller/requirements-integration.in, charms/katib-controller/requirements-integration.txt, charms/katib-controller/requirements-unit.txt, charms/katib-controller/requirements.in, charms/katib-controller/requirements.txt, charms/katib-db-manager/requirements-integration.in, charms/katib-db-manager/requirements-integration.txt, charms/katib-db-manager/requirements-unit.txt, charms/katib-db-manager/requirements.in, charms/katib-db-manager/requirements.txt
Related to: https://github.com/canonical/charmed-kubeflow-chisme/issues/155
=> fix: cos integration (update chisme)
