charms/katib-controller/metadata.yaml, charms/katib-controller/src/crds.yaml, charms/katib-controller/src/early-stopping.json, charms/katib-controller/src/metrics-collector-sidecar.json, charms/katib-controller/src/suggestion.json, charms/katib-controller/src/webhooks.yaml
This PR introduces the following:
* feat: update template files to match 0.14.0-rc0 release
* feat: version bump katib-controller image 0.12.0->0.14.0.rc0
=> feat: image version bump and template files upgrade

charms/katib-controller/src/crds.yaml
For katib 0.14 we seem to be missing the suggestions.kubeflow.org CRD this commit adds the CRD to crds.yaml and it will be applied through pod spec like the others.
=> Add suggestions.kubeflow.org CRD

charms/katib-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/katib-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/katib-db-manager/src/charm.py, charms/katib-ui/src/charm.py
When we use `juju upgrade-charm`, a new non-leader unit gets created, then the old still-leader one gets removed, resulting in the new unit being elected as the leader.
When the `leader_elected` event is not observed, the charm is not aware of having a leader now, so it remains stuck with message 'Waiting for leadership'.
This PR adds a fix to observe this event and updates observability libs.
Note that these charms don't have unit tests, there is an issue opened for adding them.
=> Observe leader-elected event and update libs

charms/katib-ui/config.yaml, charms/katib-ui/metadata.yaml, charms/katib-ui/src/charm.py
Related to this [jira task](https://warthogs.atlassian.net/browse/KF-567?atlOrigin=eyJpIjoiN2M3MjQwZmY2NzEwNGQwMTkzYThkZTNhMzU0YmFlNmUiLCJwIjoiaiJ9) and this [feature](https://github.com/canonical/kubeflow-dashboard-operator/issues/8)
In `kubeflow-dashboard-operator` there is a `sidebar` relation with the `src/extra_config.json`. In order to add element to the sidebar proper relation needs to be established. After the relation is set, charms fills the config for given app-name from `src/extra_config.json` and reloads the configmap. Currently supporting (juju application names)
- **katib-ui** for katib
- **tensorboards-web-app** for tesorboard
Sidebar element is removed after the relation is broken.
=> feat: dynamic sidebar content

.github/workflows/integrate.yaml, charms/katib-controller/src/charm.py, charms/katib-controller/src/webhooks.yaml, examples/v1beta1/hp-tuning/random.yaml
There was a missing certificate file in the operator's volumeConfig,
and both admission and mutating webhooks were not receiving any caBundle.
This commit adds the missing certificate to enable the correct behaviour
of the katib-controller and the resources that depend on it.
NOTE: this commit must be backported to track/0.14
Fixes: #13, #19
=> fix: pass ca.crt to webhooks and make it available in volume mount

charms/katib-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py, charms/katib-ui/metadata.yaml, charms/katib-ui/requirements.txt, charms/katib-ui/src/charm.py, charms/katib-ui/src/templates/auth_manifests.yaml.j2, tests/test_charms.py, tox.ini
This PR rewrites the katib-ui charm from podspec to sidecar
- added the latest KubernetesServicePatch library
- modified metadata.yaml of katb-ui to include `containers`, and removed `min-juju-version` and `series` not used in sidecar
- updated ops library version in requirements.txt to latest
- defined the pebble layer for sidecar, and added `update_layer` method to update the layer on configuration change
- added helper methods `check_container_connection` and `handle_ingress`
- updated charm events
- updated bundle integration tests to include `trust` argument when deploying katib-ui charm
- added a template for the roles and used lightkube to create them
=> Convert katib-ui to sidecar

charms/katib-controller/src/crds.yaml, charms/katib-controller/src/defaultTrialTemplate.yaml, charms/katib-controller/src/early-stopping.json, charms/katib-controller/src/enasCPUTemplate.yaml, charms/katib-controller/src/metrics-collector-sidecar.json, charms/katib-controller/src/pytorchJobTemplate.yaml, charms/katib-controller/src/suggestion.json, charms/katib-ui/src/templates/auth_manifests.yaml.j2
This PR updates the manifest and json files to match the upstream RC. 
This PR is based on kubeflow/manifests#2367, thus all manifests were rendered using the following command on that branch:
`kustomize build apps/katib/upstream/installs/katib-with-kubeflow | tee katib.manifests`
=> katib-controller/ui manifest upgrade 0.14.0 -> 0.15.0.rc.0

charms/katib-ui/metadata.yaml
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
=> feat: localize SDI schemas

.github/workflows/integrate.yaml, charms/katib-ui/requirements.txt, charms/katib-ui/src/charm.py
Implements the fix described in bundle-kubeflow#541
Notes to reviewers about CI:
* failures in library checks can be ignored (this is patching an old release anyway - we will not bump the libraries here)
* failures in publish are expected - our automated publishing on `pull_request` does not work when opening PRs against `track/*` branches
=> fix: bump serialized-data-interface to 0.4.0 on track/0.14

.github/workflows/publish.yaml, .github/workflows/release.yaml
This fixes failures in the charm publishing CI by pinning ubuntu to 20.04 for all charm building.  
Like with #55, for the PR:
* failures in library checks can be ignored (this is patching an old release anyway - we will not bump the libraries here)
* failures in publish are expected - our automated publishing on pull_request does not work when opening PRs against track/* branches
On merge, the publish tasks should work.
=> fix: pin ubuntu to 20.04 for charm building CI

charms/katib-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py, charms/katib-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_sidebar.py, charms/katib-ui/metadata.yaml, charms/katib-ui/src/charm.py
Adds the sidebar relation for kubeflow-dashboard, plus the library to manage it, replacing a previous iteration of the sidebar relation.  This allows this charm to request a link in the kubeflow dashboard's sidebar.
=> feat: add kubeflow-dashboard sidebar relation

tools/get-images.sh
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/0.15 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
=> feat: updated get images script without branch checkout for track/0.15

charms/katib-controller/requirements.txt, charms/katib-db-manager/requirements.txt, charms/katib-ui/requirements.txt, requirements-integration.in, requirements-integration.txt
Bump these package versions to avoid the issues described in https://github.com/canonical/bundle-kubeflow/issues/648.
Part of https://github.com/canonical/bundle-kubeflow/issues/648
=> build: bump juju 2.9.44.0, sdi->0.7.0, pyyaml->6.0.1

.github/workflows/integrate.yaml, charms/katib-db-manager/tests/unit/test_operator.py, tox.ini
fixes #100
* fix the `test_update_status` unit test by adding required db relation
* enable unit tests of `katib-db-manager` in the CI and add it to the tox file
=> feat: enable and fix katib-db-manager unit tests

.github/workflows/integrate.yaml
Provide the full tox environment name (i.e. `katib-controller-integration`) when running the controller integration tests through the CI to ensure the workflow works with the latest tox release (i.e. 4.9.0).
Closes #119
=> tox: Fix command for controller integration tests

tests/assets/crs/experiments/tfjob-mnist-with-summaries.yaml, tests/integration/test_katib_experiments.py
Details in #103 
add an experiment to integration tests that tests the `katib/cmd/metricscollector/v1beta1/tfevent-metricscollector` image.
deploys `training-operator` due to this type of experiment being reliant on the TFJob CRD.
=> feat: add TensorFlowEvent experiment to integration tests

charms/katib-db-manager/src/charm.py, charms/katib-db-manager/tests/unit/test_operator.py
As a temporary fix to #128 , disables the pebble health check is to be disabled in the code with a comment linking to this issue, to be re-enabled once the rock is integrated.
=> fix: disable pebble health checks

charms/katib-ui/src/charm.py
This enables using a rock as a drop-in replacement for the upstream docker image
Fixes #158
=> add `working-dir` to the katib-ui charm's pebble service

charms/katib-ui/src/charm.py
Changes katib-ui charm to correctly access the container by the container name, not by the application name.
Fixes #156
=> fix misnamed container reference in katib-ui charm

.github/workflows/integrate.yaml
addresses https://github.com/canonical/bundle-kubeflow/issues/813 in `track/0.16`
backports 25d7c1cab6f9c0f9a14411f1d074dac68c9573a9
=> ci: Decrease root-reserve-mb to fit the new runner storage (#168)

charms/katib-controller/src/grafana_dashboards/katib_saved_no_templating.json.tmpl
Backport the following:
* Add `ckf` and `katib` tag to katib-controller's grafana dashboard.
* Fix `datasource` field
* Fix current experiments & trials panel by:
* adding a `legendFormat` field
* converting it to a time series & mapping no value to 0 in order to account
for the fact that katib-controller doesn't output any `current` metrics when
there is no experiment or trial running.
Ref canonical/bundle-kubeflow#856
Ref canonical/bundle-kubeflow#834
=> backport(fix): Add `datasource` field to dashboard's target and tags from #172

tests/integration/test_charms.py, tests/integration/test_katib_experiments.py
This commit pins all charms that get deployed from Charmhub to a compatible version to the CKF 1.8 release. 
Part of canonical/bundle-kubeflow#863
=> tests: pin deployed charms to a CKF 1.8 compatible version

tests/integration/test_charms.py, tests/integration/test_katib_experiments.py
This commit pins all charms that get deployed from Charmhub to a latest/edge or suggested versions. 
Part of canonical/bundle-kubeflow#863
=> tests: pin deployed charms to a latest and stable version

.gitignore, charms/katib-controller/charmcraft.yaml, charms/katib-controller/lib/charms/mlops_libs/v0/k8s_service_info.py, charms/katib-controller/metadata.yaml, charms/katib-controller/requirements-unit.txt, charms/katib-controller/requirements.in, charms/katib-controller/requirements.txt, charms/katib-controller/src/charm.py, charms/katib-controller/src/components/k8s_service_info_requirer_component.py, charms/katib-controller/src/components/pebble_component.py, charms/katib-controller/tests/integration/test_charm.py, charms/katib-controller/tests/unit/test_charm.py, charms/katib-db-manager/charmcraft.yaml, charms/katib-db-manager/lib/charms/mlops_libs/v0/k8s_service_info.py, charms/katib-db-manager/metadata.yaml, charms/katib-db-manager/requirements-unit.txt, charms/katib-db-manager/requirements.in, charms/katib-db-manager/requirements.txt, charms/katib-db-manager/src/charm.py, tests/integration/test_charms.py, tests/integration/test_katib_experiments.py
This PR introduces a `k8s-service-info` between katib-controller and katib-db-manager. This addresses the issue below. Read the [summary comment](https://github.com/canonical/bundle-kubeflow/issues/893#issuecomment-2142022677) for a quick overview of the issue.
Note that this means that `katib-controller` will require a relation to `katib-db-manager` in order to start its pebble service, which we will need to introduce in the `latest/edge` bundle.
1. Deploy AKS cluster [following the guide](https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-aks). You can always check the [deploy-to-aks](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml) workflow for the commands the CI follows. Note that Juju 3.5 should be used but right now is broken …
=> fix: Introduce `k8s-service-info` between katib-controller and katib-db-manager

charms/katib-controller/tests/integration/test_charm.py
Follow up PR to #185
Tests can now deploy katib-db-manager with the `k8s-service-info` relation from `latest/edge`.
Ref canonical/bundle-kubeflow#893
=> chore: fix katib-controller integration test

.github/workflows/integrate.yaml, charms/katib-db-manager/lib/charms/loki_k8s/v1/loki_push_api.py, charms/katib-db-manager/metadata.yaml, charms/katib-db-manager/requirements-integration.in, charms/katib-db-manager/requirements-integration.txt, charms/katib-db-manager/requirements-unit.txt, charms/katib-db-manager/requirements.in, charms/katib-db-manager/requirements.txt, charms/katib-db-manager/src/charm.py, charms/katib-db-manager/tests/integration/test_charm.py, charms/katib-db-manager/tests/unit/test_operator.py
Added logging relation and cos integration tests from chisme.
Fix integrations test and add them to CI.
fixes: #186
How I tested it:
from terminal
```bash
$ tox -e integration -- --model kubeflow --keep-models
$ juju remove-relation katib-db:mysql katib-db-manager:mysql
$ juju consume u1-k8s:cos.loki-logging
$ juju integrate grafana-agent-k8s loki-logging
$ juju refresh katib-db-manager --path ./katib-db-manager_ubuntu-20.04-amd64.charm --force-units
```
I visit `http://<ip>/cos-grafana/explore` to explore the logs and see:
=> Add logging relation katib-db-manager

charms/katib-ui/lib/charms/loki_k8s/v1/loki_push_api.py, charms/katib-ui/metadata.yaml, charms/katib-ui/requirements.in, charms/katib-ui/requirements.txt, charms/katib-ui/src/charm.py
Added logging relation and cos integration tests from chisme.
fixes: #188
How I tested it:
from terminal
```bash
$ tox -e bundle-integration -- --keep-models -k test_deploy_katib_charms
$ juju switch test-charms-9c49
u1-k8s:admin/test-charms-w88h -> u1-k8s:admin/test-charms-9c49
$ juju deploy grafana-agent-k8s --trust
Deployed "grafana-agent-k8s" from charm-hub charm "grafana-agent-k8s", revision 68 in channel latest/stable on ubuntu@22.04/stable
$ juju consume u1-k8s:cos.loki-logging                        
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate loki-logging grafana-agent-k8s
$ juju integrate katib-ui:logging grafana-agent-k8s
$ kubectl logs -n test-charms-9c49 katib-ui-0 --container katib-ui --tail 100 | grep '\[katib-ui\]'
2024-06-17T16:06:04.414Z …
```
=> Add logging relation katib-ui

.github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
=> ci: use juju 3.4/stable instead of 3.5/stable in track 0.16

charms/katib-ui/charmcraft.yaml
Adding the rust toolchain and other dependencies to avoid issues at build time.
Part of canonical/bundle-kubeflow#989
=> build: add rust toolchain and other build packages

charms/katib-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219
=> chore: bump dashboard links lib

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/0.16

.github/workflows/integrate.yaml, .gitignore, charms/katib-controller/terraform/README.md, charms/katib-controller/terraform/main.tf, charms/katib-controller/terraform/outputs.tf, charms/katib-controller/terraform/variables.tf, charms/katib-controller/terraform/versions.tf, charms/katib-controller/tox.ini, charms/katib-db-manager/terraform/README.md, charms/katib-db-manager/terraform/main.tf, charms/katib-db-manager/terraform/outputs.tf, charms/katib-db-manager/terraform/variables.tf, charms/katib-db-manager/terraform/versions.tf, charms/katib-db-manager/tox.ini, charms/katib-ui/terraform/README.md, charms/katib-ui/terraform/main.tf, charms/katib-ui/terraform/outputs.tf, charms/katib-ui/terraform/variables.tf, charms/katib-ui/terraform/versions.tf, charms/katib-ui/tox.ini
Create a `terraform/` directory for each of the charms that hosts their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in canonical/argo-operators#198.
To test the modules:
- Clone the repository and switch this PR's branch.
- For each charm:
- `cd` into its directory 
- First run `tox -e tflint` to ensure that linting is correct
- Create a juju controller and a model name `kubeflow`
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.
Ref #236 
Ref #237 
Ref #239
=> feat: Add terraform modules for katib-{controller,db-manager,ui}

.github/workflows/integrate.yaml, .gitignore, charms/katib-controller/terraform/README.md, charms/katib-controller/terraform/main.tf, charms/katib-controller/terraform/outputs.tf, charms/katib-controller/terraform/variables.tf, charms/katib-controller/terraform/versions.tf, charms/katib-controller/tox.ini, charms/katib-db-manager/terraform/README.md, charms/katib-db-manager/terraform/main.tf, charms/katib-db-manager/terraform/outputs.tf, charms/katib-db-manager/terraform/variables.tf, charms/katib-db-manager/terraform/versions.tf, charms/katib-db-manager/tox.ini, charms/katib-ui/terraform/README.md, charms/katib-ui/terraform/main.tf, charms/katib-ui/terraform/outputs.tf, charms/katib-ui/terraform/variables.tf, charms/katib-ui/terraform/versions.tf, charms/katib-ui/tox.ini
Create a `terraform/` directory for each of the charms that hosts their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in https://github.com/canonical/argo-operators/pull/198.
Closes https://github.com/canonical/katib-operators/issues/236 
Closes https://github.com/canonical/katib-operators/issues/237 
Closes https://github.com/canonical/katib-operators/issues/239
=> feat: Backport terraform modules for katib-{controller,db-manager,ui} from #240 

.github/workflows/integrate.yaml, tox.ini
Closes https://github.com/canonical/katib-operators/issues/116
Bumped into it while working for https://github.com/canonical/katib-operators/issues/260
- Uses the `tox` environment for linting, instead of pulling the dependencies in the action
- Updates the lint command to exclude on of the templates, that was messing with spell checking
=> Use tox for lint checks

charms/katib-ui/metadata.yaml
Integrate katib-ui:v0.18.0-c84f19c rock in preparation for the 0.18 release
=> chore: integrate katib-ui:v0.18.0-c84f19c rock

tests/integration/test_charms.py
Deploy istio-pilot. This is required after the change in
canonical/kubeflow-profiles-operator#225.
Close #297
=> fix(tests): Deploy istio-pilot

charms/katib-controller/charmcraft.yaml, charms/katib-controller/constraints.txt, charms/katib-db-manager/charmcraft.yaml, charms/katib-db-manager/constraints.txt, charms/katib-ui/charmcraft.yaml, charms/katib-ui/constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints to the `setuptools-scm` to avoid install loops for these charms dependencies, as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
Fixes #293
Tests are failing due to #297 which is fixed by #298.
=> fix(workaround): set constraints to setuptools-scm to avoid install loops

charms/katib-controller/requirements-integration.txt, charms/katib-controller/tests/integration/charms_dependencies.py, charms/katib-controller/tests/integration/test_charm.py, charms/katib-db-manager/requirements-integration.txt, charms/katib-db-manager/tests/integration/charms_dependencies.py, charms/katib-db-manager/tests/integration/test_charm.py, requirements-integration.in, requirements-integration.txt, tests/integration/charms_dependencies.py, tests/integration/test_charms.py, tests/integration/test_katib_experiments.py
Move dependency charms deployed during tests to a separate file called
charms_dependencies.py. This enables programmatic access to them and
thus updating them centrally, probably with the use of `kfcicli`. This
uses the `CharmSpec` dataclass from chisme.
Ref canonical/bundle-kubeflow/issues/1256
=> refactor(tests): Move dependency charms to a separate file

charms/katib-controller/tests/integration/test_charm.py
Part of: https://github.com/canonical/bundle-kubeflow/issues/1272 
Removes the specific images from integration tests. Now we load them from `default-custom-images.json`
=> refactor: fetch test data from default-custom-images
